spring.application.name=caresync
spring.thymeleaf.cache=false
spring.web.resources.static-locations=classpath:/static/

# Povezivanje sa bazom (CareSync_DB kreiraj u MySQL Workbench-u pre pokretanja)
spring.datasource.url=jdbc:mysql://localhost:3306/caresync_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin

# JPA / Hibernate pode?avanja
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Port na kome radi backend
server.port=8080
